export const localProducts = [
    // T-SHIRTS (Oversize)
    {
        _id: 'local_1',
        name: 'LOST SOUL OVERSIZED T-SHIRT',
        slug: 'lost-soul-oversized-t-shirt',
        description: 'Premium white oversized t-shirt with bird graphic and star detail.',
        shortDescription: 'Premium white oversized t-shirt.',
        mainCategory: 'T-SHIRTS',
        subCategory: 'Oversize',
        price: 699,
        sizes: [
            { size: 'S', available: true },
            { size: 'M', available: true },
            { size: 'L', available: true },
            { size: 'XL', available: true }
        ],
        images: [{ url: '/images/products/lost-soul.jpg', alt: 'Lost Soul T-Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_2',
        name: 'SPEED FORMULA CREAM T-SHIRT',
        slug: 'speed-formula-t-shirt',
        description: 'Cream/Off-white t-shirt featuring a vintage racing car graphic.',
        shortDescription: 'Off-white graphic t-shirt.',
        mainCategory: 'T-SHIRTS',
        subCategory: 'Oversize',
        price: 799,
        sizes: [{ size: 'M', available: true }, { size: 'L', available: true }],
        images: [{ url: '/images/products/speed.jpg', alt: 'Speed T-Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_3',
        name: 'BETTER DAYS BLACK GRAPHIC T-SHIRT',
        slug: 'better-days-black-t-shirt',
        description: 'Heavyweight black t-shirt with "Better Days" script and glowing star design.',
        shortDescription: 'Black graphic t-shirt.',
        mainCategory: 'T-SHIRTS',
        subCategory: 'Oversize',
        price: 899,
        sizes: [{ size: 'S', available: true }, { size: 'M', available: true }],
        images: [{ url: '/images/products/better-days.jpg', alt: 'Better Days T-Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_4',
        name: 'PURPLE FIGURE GRAPHIC T-SHIRT',
        slug: 'purple-figure-t-shirt',
        description: 'Purple aesthetic graphic t-shirt with modern art print.',
        shortDescription: 'Purple graphic t-shirt.',
        mainCategory: 'T-SHIRTS',
        subCategory: 'Oversize',
        price: 749,
        sizes: [{ size: 'L', available: true }, { size: 'XL', available: true }],
        images: [{ url: '/images/products/purple-figure.jpg', alt: 'Purple Figure T-Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_5',
        name: 'APPROACH MAROON OVERSIZED T-SHIRT',
        slug: 'approach-maroon-t-shirt',
        description: 'Deep maroon oversized t-shirt with minimal branding.',
        shortDescription: 'Maroon oversized t-shirt.',
        mainCategory: 'T-SHIRTS',
        subCategory: 'Oversize',
        price: 699,
        sizes: [{ size: 'M', available: true }, { size: 'XXL', available: true }],
        images: [{ url: '/images/products/approach.jpg', alt: 'Approach T-Shirt', isPrimary: true }],
        status: 'active'
    },

    // SHIRTS (Full Sleeve Shirts)
    {
        _id: 'local_s1',
        name: 'GREEN STRIPED POPLIN SHIRT',
        slug: 'green-striped-shirt',
        description: 'Premium green and white striped button-down shirt.',
        shortDescription: 'Green striped formal shirt.',
        mainCategory: 'SHIRTS',
        subCategory: 'Full Sleeve Shirts',
        price: 1299,
        sizes: [{ size: 'M', available: true }, { size: 'L', available: true }],
        images: [{ url: '/images/products/shirt-1.jpg', alt: 'Green Striped Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_s2',
        name: 'BLUE OXFORD STRIPED SHIRT',
        slug: 'blue-striped-shirt-1',
        description: 'Classic blue striped oxford shirt for a sharp look.',
        shortDescription: 'Blue striped shirt.',
        mainCategory: 'SHIRTS',
        subCategory: 'Full Sleeve Shirts',
        price: 1399,
        sizes: [{ size: 'L', available: true }],
        images: [{ url: '/images/products/shirt-2.jpg', alt: 'Blue Striped Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_s3',
        name: 'MODERN BLUE STRIPE SHIRT',
        slug: 'blue-striped-shirt-2',
        description: 'Modern fit blue striped shirt with premium finish.',
        shortDescription: 'Modern blue stripe shirt.',
        mainCategory: 'SHIRTS',
        subCategory: 'Full Sleeve Shirts',
        price: 1299,
        sizes: [{ size: 'S', available: true }, { size: 'M', available: true }],
        images: [{ url: '/images/products/shirt-3.jpg', alt: 'Modern Blue Stripe', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_s4',
        name: 'BLACK FLORAL CASUAL SHIRT',
        slug: 'black-floral-shirt',
        description: 'Elegant black shirt with subtle floral patterns.',
        shortDescription: 'Black floral shirt.',
        mainCategory: 'SHIRTS',
        subCategory: 'Full Sleeve Shirts',
        price: 1499,
        sizes: [{ size: 'M', available: true }, { size: 'XL', available: true }],
        images: [{ url: '/images/products/shirt-4.jpg', alt: 'Black Floral Shirt', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_s5',
        name: 'BLACK EMBROIDERED PREMIUM SHIRT',
        slug: 'black-embroidered-shirt',
        description: 'Premium black shirt with intricate embroidery details.',
        shortDescription: 'Black embroidered shirt.',
        mainCategory: 'SHIRTS',
        subCategory: 'Full Sleeve Shirts',
        price: 1699,
        sizes: [{ size: 'L', available: true }, { size: 'XXL', available: true }],
        images: [{ url: '/images/products/shirt-5.jpg', alt: 'Black Embroidered Shirt', isPrimary: true }],
        status: 'active'
    },

    // JEANS (Straight Fit)
    {
        _id: 'local_j1',
        name: 'VINTAGE WASH RELAXED JEANS',
        slug: 'vintage-wash-jeans',
        description: 'Light blue vintage wash relaxed fit denim jeans.',
        shortDescription: 'Relaxed fit light wash jeans.',
        mainCategory: 'JEANS',
        subCategory: 'Straight Fit',
        price: 1499,
        sizes: [{ size: 'M', available: true }, { size: 'L', available: true }],
        images: [{ url: '/images/products/jeans-1.jpg', alt: 'Vintage Wash Jeans', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_j2',
        name: 'CLASSIC BLUE DENIM',
        slug: 'classic-denim',
        description: 'Classic blue denim with a straight leg fit.',
        shortDescription: 'Classic straight fit denim.',
        mainCategory: 'JEANS',
        subCategory: 'Straight Fit',
        price: 1599,
        sizes: [{ size: 'S', available: true }, { size: 'M', available: true }],
        images: [{ url: '/images/products/jeans-2.jpg', alt: 'Classic Denim', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_j3',
        name: 'LIGHT WASH BAGGY JEANS',
        slug: 'light-wash-baggy-jeans',
        description: 'Streetwear-style light wash baggy denim.',
        shortDescription: 'Light wash baggy jeans.',
        mainCategory: 'JEANS',
        subCategory: 'Baggy',
        price: 1799,
        sizes: [{ size: 'L', available: true }, { size: 'XL', available: true }],
        images: [{ url: '/images/products/jeans-3.jpg', alt: 'Light Wash Baggy Jeans', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_j4',
        name: 'DARK NAVY TROUSERS',
        slug: 'dark-navy-trousers',
        description: 'Premium dark navy cotton trousers.',
        shortDescription: 'Dark navy trousers.',
        mainCategory: 'JEANS',
        subCategory: 'Straight Fit',
        price: 1899,
        sizes: [{ size: 'M', available: true }],
        images: [{ url: '/images/products/jeans-4.jpg', alt: 'Dark Navy Trousers', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_j5',
        name: 'DARK WASH STRAIGHT DENIM',
        slug: 'dark-wash-denim',
        description: 'Classic dark wash denim with a straight fit.',
        shortDescription: 'Dark wash straight denim.',
        mainCategory: 'JEANS',
        subCategory: 'Straight Fit',
        price: 1699,
        sizes: [{ size: 'S', available: true }, { size: 'XL', available: true }],
        images: [{ url: '/images/products/jeans-5.jpg', alt: 'Dark Wash Denim', isPrimary: true }],
        status: 'active'
    },

    // POLOS
    {
        _id: 'local_p1',
        name: 'BLACK RIBBED PREMIUM POLO',
        slug: 'black-ribbed-polo',
        description: 'Premium black ribbed polo shirt with a slim fit.',
        shortDescription: 'Black ribbed polo.',
        mainCategory: 'POLOS',
        subCategory: '',
        price: 999,
        sizes: [{ size: 'M', available: true }, { size: 'L', available: true }],
        images: [{ url: '/images/products/black-ribbed-polo.jpg', alt: 'Black Ribbed Polo', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_p2',
        name: 'CREAM & GREEN STRIPED POLO',
        slug: 'cream-green-polo',
        description: 'Cream and green striped polo for a fresh summer look.',
        shortDescription: 'Cream green striped polo.',
        mainCategory: 'POLOS',
        subCategory: '',
        price: 1099,
        sizes: [{ size: 'L', available: true }, { size: 'XL', available: true }],
        images: [{ url: '/images/products/cream-green-polo.jpg', alt: 'Cream Green Polo', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_p3',
        name: 'CREAM & NAVY TEXTURED POLO',
        slug: 'cream-navy-polo',
        description: 'Textured cream and navy polo with premium cotton feel.',
        shortDescription: 'Cream navy textured polo.',
        mainCategory: 'POLOS',
        subCategory: '',
        price: 1199,
        sizes: [{ size: 'S', available: true }, { size: 'M', available: true }],
        images: [{ url: '/images/products/cream-navy-polo.jpg', alt: 'Cream Navy Polo', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_p4',
        name: 'NAVY & BROWN CONTRAST POLO',
        slug: 'navy-brown-polo',
        description: 'Navy polo with brown contrast collar and cuffs.',
        shortDescription: 'Navy brown contrast polo.',
        mainCategory: 'POLOS',
        subCategory: '',
        price: 1099,
        sizes: [{ size: 'M', available: true }, { size: 'L', available: true }],
        images: [{ url: '/images/products/navy-brown-polo.jpg', alt: 'Navy Brown Polo', isPrimary: true }],
        status: 'active'
    },
    {
        _id: 'local_p5',
        name: 'NAVY KNIT PREMIUM POLO',
        slug: 'navy-knit-polo',
        description: 'Heavyweight navy knit polo for a premium feel.',
        shortDescription: 'Navy knit premium polo.',
        mainCategory: 'POLOS',
        subCategory: '',
        price: 1299,
        sizes: [{ size: 'XL', available: true }, { size: 'XXL', available: true }],
        images: [{ url: '/images/products/navy-knit-polo.jpg', alt: 'Navy Knit Polo', isPrimary: true }],
        status: 'active'
    }
];
